# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    build: /docker/
    ports:
      - "8001:8001"
    restart: on-failure
    networks:
      - hr-net
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/src/usr/app

  db:
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: hairun
    networks:
      - hr-net

  admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - hr-net
    
  networks:
    hr-net:
      driver: bridge